name: Linux Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.9'
      - name: Build
        run: |
          echo "Venv setup"
          python3 -m venv .venv
          source ./.venv/bin/activate
          echo "Installing dependencies"
          pip install -e ./
          echo "Building style"
          python build_style.py
          echo "Building Linux"
          cd ./scripts/
          sh ./build_linux.sh
      - name: Zipping
        run: |
          echo "Zipping to Blender_Launcher_${{ env.RELEASE_VERSION }}_Ubuntu_x64.zip"
          cd ./dist/release/
          zip Blender_Launcher_${{ env.RELEASE_VERSION }}_Ubuntu_x64.zip "./Blender Launcher"
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/release/Blender_Launcher_${{ env.RELEASE_VERSION }}_Ubuntu_x64.zip
